---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Also update bootstrap.md
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.2.0/manifests/install.yaml
  - ingress.yml

patches:
  - path: patch-argocd-cmd-params-cm.yml
