---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expenses
spec:
  defaultBackend:
    service:
      name: expenses-server
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - expenses