replicaCount: 1

config:
  # Scope the cnpg operator to manage cnpg clusters in any
  # namespace in the Kubernetes cluster. This allows creating
  # databases in the same namespace as the applications using
  # them.
  clusterWide: true
