---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/admin-minter"
            backend:
              service:
                name: admin-minter
                port:
                  number: 80
          - pathType: Prefix
            path: "/homelab-minter"
            backend:
              service:
                name: homelab-minter
                port:
                  number: 80
  defaultBackend:
    service:
      name: admin-minter
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - homelab
